on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create document
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Convert to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.0.0
      with:
        texFile: ./src/main.tex
    - name: Store pdf
      uses: actions/upload-artifact@v4.4.1
      with:
        name: tourist_cv.pdf
        path: ./src/tourist_cv.pdf